/* ============================================================
   NUMLAND - Learning Catalog and Level Rules
   ============================================================ */

'use strict';

window.NUMLAND_LEVELS = {
  1: {
    id: 1,
    label: 'Level 1',
    ageGroup: 'Ages 3-4',
    title: 'Number Discovery',
    icon: '🌟',
    message: 'Let\'s play something just right for you.',
    progression: 'Start with counting 1-5, then 1-10.',
    unlockedConcepts: ['counting', 'number recognition', 'sorting', 'shapes', 'tracing', 'sequencing'],
  },
  2: {
    id: 2,
    label: 'Level 2',
    ageGroup: 'Ages 5-6',
    title: 'Early Math Explorers',
    icon: '🌱',
    message: 'Great job! You are ready for early math explorer games.',
    progression: 'Begin with visual addition under 10, then under 20.',
    unlockedConcepts: ['counting to 50', 'compare', 'addition', 'subtraction', 'patterns', 'number bonds', 'skip counting'],
  },
  3: {
    id: 3,
    label: 'Level 3',
    ageGroup: 'Ages 7-8',
    title: 'Math Builders',
    icon: '🏗️',
    message: 'Build your skills step-by-step like a math architect.',
    progression: 'Start with equal groups, then multiplication facts.',
    unlockedConcepts: ['place value', 'regrouping', 'multiplication intro', 'skip counting', 'arrays', 'time', 'money', 'measurement', 'word problems'],
  },
  4: {
    id: 4,
    label: 'Level 4',
    ageGroup: 'Ages 9-10',
    title: 'Math Adventurers',
    icon: '🗺️',
    message: 'Keep exploring, little mathematician!',
    progression: 'Start with visual fractions, then abstract fraction problems.',
    unlockedConcepts: ['multiplication', 'division', 'fractions', 'geometry', 'area', 'measurement conversion', 'multi-step problem solving', 'remainders', 'logic puzzles'],
  },
};

window.NUMLAND_ACTIVITY_CATALOG = [
  // Level 1
  {
    id: 'l1-count-animals',
    title: 'Count the Animals',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'counting',
    difficulty: 'easy',
    instructions: 'Count cute animals and pick the matching number.',
    rewardType: 'stars',
    visualAssets: ['animals', 'number cards'],
  },
  {
    id: 'l1-number-match',
    title: 'Number Match',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'number recognition',
    difficulty: 'easy',
    instructions: 'Match number cards 1-10 to groups of objects.',
    rewardType: 'stickers',
    visualAssets: ['number cards', 'object groups'],
  },
  {
    id: 'l1-bead-tray',
    title: 'Bead Counting Tray',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'counting',
    difficulty: 'easy',
    instructions: 'Drag Montessori beads into the tray and count them.',
    rewardType: 'stars',
    visualAssets: ['beads', 'tray'],
  },
  {
    id: 'l1-shape-sort',
    title: 'Shape Sorting',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'shapes',
    difficulty: 'easy',
    instructions: 'Sort circles, squares, triangles, and stars by shape.',
    rewardType: 'garden',
    visualAssets: ['shape tiles', 'shape baskets'],
  },
  {
    id: 'l1-color-sort',
    title: 'Color Sorting',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'sorting',
    difficulty: 'easy',
    instructions: 'Sort objects by color into matching baskets.',
    rewardType: 'stars',
    visualAssets: ['color tokens', 'baskets'],
  },
  {
    id: 'l1-big-small',
    title: 'Big or Small',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'compare',
    difficulty: 'easy',
    instructions: 'Choose which group has more or fewer objects.',
    rewardType: 'badges',
    visualAssets: ['group cards'],
  },
  {
    id: 'l1-trace',
    title: 'Number Tracing 1-10',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'tracing',
    difficulty: 'easy',
    instructions: 'Trace numbers 1-10 with dotted guides.',
    rewardType: 'stars',
    visualAssets: ['trace canvas'],
  },
  {
    id: 'l1-missing-number',
    title: 'Missing Number',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'sequencing',
    difficulty: 'easy',
    instructions: 'Fill the missing number in a sequence from 1-10.',
    rewardType: 'stickers',
    visualAssets: ['number sequence cards'],
  },
  {
    id: 'l1-garden-count',
    title: 'Counting Garden',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'counting',
    difficulty: 'easy',
    instructions: 'Plant flowers by counting seeds.',
    rewardType: 'garden',
    visualAssets: ['seeds', 'flower pots'],
  },

  // Level 2
  {
    id: 'l2-count-50',
    title: 'Count to 50',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'counting to 50',
    difficulty: 'easy',
    instructions: 'Practice counting objects up to 50.',
    rewardType: 'stars',
    visualAssets: ['number line'],
  },
  {
    id: 'l2-number-order',
    title: 'Number Order',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'sequencing',
    difficulty: 'easy',
    instructions: 'Arrange number tiles in the correct order.',
    rewardType: 'stars',
    visualAssets: ['number tiles'],
  },
  {
    id: 'l2-compare',
    title: 'More, Less, Equal',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'compare',
    difficulty: 'easy',
    instructions: 'Compare two visual groups using more, less, or equal.',
    rewardType: 'badges',
    visualAssets: ['group counters'],
  },
  {
    id: 'l2-add-basket',
    title: 'Addition Basket',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'addition',
    difficulty: 'medium',
    instructions: 'Add fruits together using visual counters.',
    rewardType: 'stars',
    visualAssets: ['fruit counters', 'baskets'],
  },
  {
    id: 'l2-sub-snack',
    title: 'Subtraction Snack',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'subtraction',
    difficulty: 'medium',
    instructions: 'Remove snacks and count how many are left.',
    rewardType: 'stars',
    visualAssets: ['snack counters'],
  },
  {
    id: 'l2-pattern-builder',
    title: 'Pattern Builder',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'patterns',
    difficulty: 'easy',
    instructions: 'Complete repeating patterns with colors and shapes.',
    rewardType: 'stickers',
    visualAssets: ['pattern tiles'],
  },
  {
    id: 'l2-number-bonds',
    title: 'Number Bonds',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'number bonds',
    difficulty: 'medium',
    instructions: 'Build numbers using two smaller groups.',
    rewardType: 'stars',
    visualAssets: ['bond circles'],
  },
  {
    id: 'l2-skip-count',
    title: 'Skip Counting 2s, 5s, 10s',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'skip counting',
    difficulty: 'medium',
    instructions: 'Practice skip counting by 2s, 5s, and 10s.',
    rewardType: 'stars',
    visualAssets: ['skip path'],
  },
  {
    id: 'l2-missing-addend',
    title: 'Missing Addends',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'addition',
    difficulty: 'medium',
    instructions: 'Find the missing number using objects.',
    rewardType: 'badges',
    visualAssets: ['object groups'],
  },
  {
    id: 'l2-bead-add',
    title: 'Montessori Bead Addition',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'addition',
    difficulty: 'medium',
    instructions: 'Add bead bars together visually.',
    rewardType: 'stars',
    visualAssets: ['bead bars'],
  },

  // Level 3
  {
    id: 'l3-place-value',
    title: 'Place Value Blocks',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'place value',
    difficulty: 'medium',
    instructions: 'Build numbers using hundreds, tens, and ones blocks.',
    rewardType: 'stars',
    visualAssets: ['base-ten blocks'],
  },
  {
    id: 'l3-add-builder',
    title: 'Addition Builder',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'addition regrouping',
    difficulty: 'medium',
    instructions: 'Solve two-digit addition with visual regrouping support.',
    rewardType: 'stars',
    visualAssets: ['base-ten blocks'],
  },
  {
    id: 'l3-sub-builder',
    title: 'Subtraction Builder',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'subtraction regrouping',
    difficulty: 'medium',
    instructions: 'Solve two-digit subtraction using base-ten blocks.',
    rewardType: 'stars',
    visualAssets: ['base-ten blocks'],
  },
  {
    id: 'l3-mult-garden',
    title: 'Multiplication Garden',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'multiplication intro',
    difficulty: 'medium',
    instructions: 'Understand multiplication as equal groups.',
    rewardType: 'garden',
    visualAssets: ['groups', 'flowers'],
  },
  {
    id: 'l3-skip-path',
    title: 'Skip Counting Path',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'skip counting',
    difficulty: 'medium',
    instructions: 'Jump by 2s, 3s, 5s, and 10s.',
    rewardType: 'stars',
    visualAssets: ['path markers'],
  },
  {
    id: 'l3-array-builder',
    title: 'Array Builder',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'arrays',
    difficulty: 'medium',
    instructions: 'Create multiplication arrays using tiles.',
    rewardType: 'badges',
    visualAssets: ['array tiles'],
  },
  {
    id: 'l3-word-problems',
    title: 'Simple Word Problems',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'word problems',
    difficulty: 'medium',
    instructions: 'Solve short visual story problems.',
    rewardType: 'stars',
    visualAssets: ['story cards'],
  },
  {
    id: 'l3-time',
    title: 'Time Practice',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'time',
    difficulty: 'medium',
    instructions: 'Read simple analog and digital clocks.',
    rewardType: 'stars',
    visualAssets: ['clock faces'],
  },
  {
    id: 'l3-money-match',
    title: 'Money Match',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'money',
    difficulty: 'medium',
    instructions: 'Match coins and bills to amounts.',
    rewardType: 'badges',
    visualAssets: ['coins', 'notes'],
  },
  {
    id: 'l3-measurement',
    title: 'Measurement Lab',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'measurement',
    difficulty: 'medium',
    instructions: 'Compare length, height, and weight.',
    rewardType: 'stars',
    visualAssets: ['rulers', 'scales'],
  },
  {
    id: 'l3-even-odd',
    title: 'Even or Odd Sorting',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'even and odd',
    difficulty: 'medium',
    instructions: 'Sort numbers into even and odd baskets.',
    rewardType: 'stars',
    visualAssets: ['number cards'],
  },

  // Level 4
  {
    id: 'l4-mult-quest',
    title: 'Multiplication Quest',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'multiplication',
    difficulty: 'medium',
    instructions: 'Practice multiplication facts in an adventure format.',
    rewardType: 'stars',
    visualAssets: ['quest cards'],
  },
  {
    id: 'l4-division-sharing',
    title: 'Division Sharing',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'division',
    difficulty: 'medium',
    instructions: 'Divide objects equally between characters.',
    rewardType: 'stars',
    visualAssets: ['share groups'],
  },
  {
    id: 'l4-fraction-pizza',
    title: 'Fraction Pizza',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'fractions',
    difficulty: 'medium',
    instructions: 'Build and compare fractions with pizza slices.',
    rewardType: 'stars',
    visualAssets: ['pizza slices'],
  },
  {
    id: 'l4-fraction-match',
    title: 'Fraction Match',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'fractions',
    difficulty: 'medium',
    instructions: 'Match visual fractions to number forms.',
    rewardType: 'badges',
    visualAssets: ['fraction cards'],
  },
  {
    id: 'l4-geometry-builder',
    title: 'Geometry Builder',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'geometry',
    difficulty: 'medium',
    instructions: 'Identify and build geometric shapes.',
    rewardType: 'stars',
    visualAssets: ['shape tools'],
  },
  {
    id: 'l4-area',
    title: 'Area Explorer',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'area',
    difficulty: 'hard',
    instructions: 'Count square tiles to find area.',
    rewardType: 'stars',
    visualAssets: ['grid tiles'],
  },
  {
    id: 'l4-measurement-challenge',
    title: 'Measurement Challenge',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'measurement',
    difficulty: 'hard',
    instructions: 'Convert simple units and compare measurements.',
    rewardType: 'badges',
    visualAssets: ['measurement cards'],
  },
  {
    id: 'l4-multi-step',
    title: 'Multi-Step Story Problems',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'word problems',
    difficulty: 'hard',
    instructions: 'Solve story problems with two or more steps.',
    rewardType: 'stars',
    visualAssets: ['story scenes'],
  },
  {
    id: 'l4-logic-path',
    title: 'Logic Puzzle Path',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'logic',
    difficulty: 'hard',
    instructions: 'Solve math puzzles to unlock the next area.',
    rewardType: 'treasure',
    visualAssets: ['puzzle path'],
  },
  {
    id: 'l4-treasure',
    title: 'Math Treasure Hunt',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'mixed review',
    difficulty: 'hard',
    instructions: 'Solve level-appropriate problems to collect treasure.',
    rewardType: 'treasure',
    visualAssets: ['maps', 'chests'],
  },
  {
    id: 'l4-missing-factor',
    title: 'Missing Factor Game',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'multiplication',
    difficulty: 'hard',
    instructions: 'Find the missing multiplication factor.',
    rewardType: 'stars',
    visualAssets: ['equation cards'],
  },
  {
    id: 'l4-remainder',
    title: 'Remainder Explorer',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'division with remainder',
    difficulty: 'hard',
    instructions: 'Understand simple division with leftovers.',
    rewardType: 'badges',
    visualAssets: ['grouping counters'],
  },
];

window.NUMLAND_GAME_CATALOG = [
  {
    gameTitle: 'Quick Math Quiz',
    gameId: 'game-quiz',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'counting',
    difficulty: 'easy',
    instructions: 'Choose the number that matches the picture or sequence.',
    questions: ['counting', 'what comes next'],
    visualAssets: ['objects', 'numbers'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Quick Math Quiz',
    gameId: 'game-quiz',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'addition and subtraction',
    difficulty: 'easy',
    instructions: 'Solve simple visual addition and subtraction under 20.',
    questions: ['addition', 'subtraction', 'compare'],
    visualAssets: ['fruit counters', 'number line'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Quick Math Quiz',
    gameId: 'game-quiz',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'place value and multiplication intro',
    difficulty: 'medium',
    instructions: 'Practice place value, skip counting, and multiplication intro.',
    questions: ['place value', 'skip counting', 'equal groups'],
    visualAssets: ['base-ten blocks', 'arrays'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Quick Math Quiz',
    gameId: 'game-quiz',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'multiplication, division, fractions',
    difficulty: 'hard',
    instructions: 'Solve multiplication, division, and fraction comparison.',
    questions: ['multiplication', 'division', 'fractions'],
    visualAssets: ['fraction cards', 'equation cards'],
    rewardType: 'treasure',
  },
  {
    gameTitle: 'Flash Cards',
    gameId: 'game-flash',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'number recognition',
    difficulty: 'easy',
    instructions: 'See a number and identify matching quantity.',
    questions: ['number facts 1-10'],
    visualAssets: ['number cards'],
    rewardType: 'stickers',
  },
  {
    gameTitle: 'Flash Cards',
    gameId: 'game-flash',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'addition and subtraction',
    difficulty: 'easy',
    instructions: 'Practice simple addition and subtraction facts.',
    questions: ['facts under 20'],
    visualAssets: ['flash cards'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Flash Cards',
    gameId: 'game-flash',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'multiplication intro',
    difficulty: 'medium',
    instructions: 'Practice skip counting and multiplication facts up to 6x6.',
    questions: ['times tables intro'],
    visualAssets: ['array cards'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Flash Cards',
    gameId: 'game-flash',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'multiplication and division',
    difficulty: 'hard',
    instructions: 'Practice multiplication and missing factors.',
    questions: ['times tables', 'missing factors'],
    visualAssets: ['equation cards'],
    rewardType: 'badges',
  },
  {
    gameTitle: 'Number Bubbles',
    gameId: 'game-bubble',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'counting sequence',
    difficulty: 'easy',
    instructions: 'Pop bubbles in order from 1 to 10.',
    questions: ['sequence 1-10'],
    visualAssets: ['number bubbles'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Number Bubbles',
    gameId: 'game-bubble',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'counting sequence',
    difficulty: 'easy',
    instructions: 'Pop bubbles in order up to 20 and by skip-count rules.',
    questions: ['sequence to 20', 'skip by 2'],
    visualAssets: ['number bubbles'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Number Bubbles',
    gameId: 'game-bubble',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'skip counting',
    difficulty: 'medium',
    instructions: 'Pop skip-count bubbles by 2, 3, 5, or 10.',
    questions: ['skip counting'],
    visualAssets: ['number bubbles'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Number Bubbles',
    gameId: 'game-bubble',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'factors and multiples',
    difficulty: 'hard',
    instructions: 'Pop bubbles that match factor/multiple rules.',
    questions: ['factors', 'multiples'],
    visualAssets: ['number bubbles'],
    rewardType: 'treasure',
  },
  {
    gameTitle: 'Count Challenge',
    gameId: 'game-count',
    level: 1,
    ageGroup: 'Ages 3-4',
    mathConcept: 'counting',
    difficulty: 'easy',
    instructions: 'Count objects up to 10 and choose the correct number.',
    questions: ['count objects'],
    visualAssets: ['object sets'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Count Challenge',
    gameId: 'game-count',
    level: 2,
    ageGroup: 'Ages 5-6',
    mathConcept: 'counting and compare',
    difficulty: 'easy',
    instructions: 'Count objects up to 20 and compare groups.',
    questions: ['counting to 20', 'more/less'],
    visualAssets: ['object sets'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Count Challenge',
    gameId: 'game-count',
    level: 3,
    ageGroup: 'Ages 7-8',
    mathConcept: 'group counting',
    difficulty: 'medium',
    instructions: 'Count groups and solve two-step counting prompts.',
    questions: ['group totals'],
    visualAssets: ['group arrays'],
    rewardType: 'stars',
  },
  {
    gameTitle: 'Count Challenge',
    gameId: 'game-count',
    level: 4,
    ageGroup: 'Ages 9-10',
    mathConcept: 'area and arrays',
    difficulty: 'hard',
    instructions: 'Count tiles and groups to solve area-style totals.',
    questions: ['array totals', 'area tiles'],
    visualAssets: ['grids'],
    rewardType: 'badges',
  },
];

window.NUMLAND_RECOMMENDED = {
  1: ['Count the Animals', 'Number Match', 'Counting Garden'],
  2: ['Addition Basket', 'Pattern Builder', 'Skip Counting 2s, 5s, and 10s'],
  3: ['Place Value Blocks', 'Array Builder', 'Time Practice'],
  4: ['Fraction Pizza', 'Geometry Builder', 'Math Treasure Hunt'],
};

window.getActivitiesForLevel = function getActivitiesForLevel(level) {
  return window.NUMLAND_ACTIVITY_CATALOG.filter(item => item.level === Number(level));
};

window.getGamesForLevel = function getGamesForLevel(level) {
  return window.NUMLAND_GAME_CATALOG.filter(item => item.level === Number(level));
};
